" Filename:      vimrc
" Description:   Vim configuration file
" Maintainer:    motw <motw@gmx.net>
" Last Modified: Sun 2011-07-10 23:38:10 (-0400)

" kein vi
set nocompatible

" ermoeglicht es den Buffer zu wechseln ohne zu speichern
set hidden

" sichere die letzten 100 Kommando/Suchen Eintraege
set history=100

" mapleader setzen
set mapleader=","

"" shortmess settings:
" f - use "(3 of 5)" instead of "(file 3 of 5)"
" i - use "[noeol]" instead of "[Incomplete last line]"
" l - use "999L, 888C" instead of "999 lines, 888 characters"
" m - use "[+]" instead of "[Modified]"
" n - use "[New]" instead of "[New File]"
" r - use "[RO]" instead of "[readonly]"
" x - use "[dos]" instead of "[dos format]", "[unix]" instead of "[unix
" format]", and "[mac]" instead of "[mac format]"
" t - truncate file message at the start if it is too long to fit on the
" command-line, "<" will appear in the left most column.
" T - trunctate other messages in the middle if they are too long to fit on
" the command line. "..." will appear in the middle.
" I - don't give the intro message when starting Vim.
set shortmess=filmnrxtTI

" filetype off, damit pathogen alles laden kann
filetype off

" pathogen Plugins/etc. laden
call pathogen#runtime_append_all_bundles()

" setzen von filetype settings, syntax, etc.
filetype plugin indent on
syntax on

" Laden der Config
runtime! config/**/*
